version: '3'
services:

  teamup-log-connector-web:
    container_name: teamup-log-connector-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/www
      - ./:/home/www
    stdin_open: true
    networks:
      - teamup-log-connector-network
    ports:
      - "80:80"

networks:
  teamup-log-connector-network:
    driver: bridge
